import { describe, expect, it } from "vitest"

import type { GeoPoint, Trace } from "./activity"
import { traceToCells, traceToSegments } from "./fog"

/**
 * Ticket `0195`. `05-fog-of-war.md` §2.2 steps 1-3.
 *
 * `traceToSegments` was extracted out of `traceToCells` so the drawn route and the revealed
 * ground come from one sanitation path. Two things have to stay true, and they are the whole
 * of this file: the extraction changed no cell, and the chords between segments do not exist.
 *
 * GEOMETRY IS SYNTHETIC, near Point Nemo — `08-security-privacy.md` §7.2, D-199. This
 * repository is public.
 */

const NEMO = { lat: -48.876, lng: -123.393 }
const R_EARTH = 6_371_008.8
const toRad = (d: number) => (d * Math.PI) / 180
const toDeg = (r: number) => (r * 180) / Math.PI

function step(from: { lat: number; lng: number }, metres: number, bearing: number) {
  return {
    lat: from.lat + toDeg((metres * Math.cos(bearing)) / R_EARTH),
    lng: from.lng + toDeg((metres * Math.sin(bearing)) / (R_EARTH * Math.cos(toRad(from.lat)))),
  }
}

function line(
  from: { lat: number; lng: number },
  bearing: number,
  count: number,
  spacingM: number,
  speedMs = 3,
  t0 = 0,
): GeoPoint[] {
  const out: GeoPoint[] = []
  for (let i = 0; i < count; i++) {
    const p = step(from, i * spacingM, bearing)
    out.push({ ...p, t: t0 + Math.round((i * spacingM * 1000) / speedMs) })
  }
  return out
}

function trace(points: GeoPoint[], gaps: Array<[number, number]> = []): Trace {
  const lats = points.map((p) => p.lat)
  const lngs = points.map((p) => p.lng)
  return {
    points,
    gaps,
    simplified: false,
    bbox: points.length
      ? [Math.min(...lngs), Math.min(...lats), Math.max(...lngs), Math.max(...lats)]
      : [0, 0, 0, 0],
    pointCount: points.length,
  }
}

const metres = (a: GeoPoint, b: GeoPoint): number => {
  const dLat = toRad(b.lat - a.lat)
  const dLng = toRad(b.lng - a.lng) * Math.cos(toRad((a.lat + b.lat) / 2))
  return Math.hypot(dLat, dLng) * R_EARTH
}

/**
 * THE CELL SETS THESE FOUR TRACES PRODUCE, pinned. Originally `0195` criterion 1; RE-PINNED AT
 * RES 11 BY `0194` (D-237), and what that cost is worth stating rather than hiding.
 *
 * **What this fixture was.** `0195` pulled `traceToSegments` out of `traceToCells`, and these ids
 * were generated by running `git show HEAD:src/domain/fog.ts` — the version BEFORE the extraction —
 * against the four traces below, then written down. That is the one assurance a refactor needs and
 * the one a snapshot of the refactored code cannot give.
 *
 * **Why it cannot stay that.** D-237 moved the canonical grid from res 10 to res 11. The
 * pre-extraction code emitted res-10 ids and no longer exists to be re-run at res 11, so the
 * comparison is not re-derivable — not stale, genuinely unavailable. Re-pinning from current code
 * turns this into a regression fixture: it still catches an unintended change to steps 0-5, and it
 * no longer proves anything about the extraction.
 *
 * **The extraction guarantee is not lost, it is discharged.** It was verified at `0195`'s close
 * against these res-10 ids, and that verification stands in the history. For provenance the
 * originals were:
 *
 *   8ad36070d0a7fff
 *   8ad36070d0affff
 *   8ad36070d0c7fff
 *   8ad36070d0cffff
 *   8ad36070d0f7fff
 *   8ad36070d767fff
 *   8ad36070d76ffff
 *   8ad36070d0a7fff
 *   8ad36070d0affff
 *   8ad36070d0c7fff
 *   8ad36070d0f7fff
 *   8ad3607540c7fff
 *   8ad3607540dffff
 *   8ad360754767fff
 *   8ad36075476ffff
 *   8ad36070d0a7fff
 *   8ad36070d0affff
 *   8ad36070d0c7fff
 *   8ad36070d0dffff
 *   8ad36070d0f7fff
 *   8ad36070d447fff
 *   8ad36070d44ffff
 *   8ad36070d717fff
 *   8ad36070d71ffff
 *   8ad36070d72ffff
 *   8ad3606b484ffff
 *   8ad3606b4a37fff
 *   8ad3606b4b17fff
 *   8ad36070d0a7fff
 *   8ad36070d0affff
 *   8ad36070d0f7fff
 *
 * They are ids and not counts because D-020 makes a cell permanent: a change that dropped one cell
 * and gained another passes every count check ever written.
 */
const PRE_EXTRACTION: Record<string, string[]> = {
  straight: [
    "8bd36070d012fff",
    "8bd36070d013fff",
    "8bd36070d016fff",
    "8bd36070d01afff",
    "8bd36070d0a0fff",
    "8bd36070d0a1fff",
    "8bd36070d0a4fff",
    "8bd36070d0a5fff",
    "8bd36070d0a8fff",
    "8bd36070d0a9fff",
    "8bd36070d0abfff",
    "8bd36070d0acfff",
    "8bd36070d0adfff",
    "8bd36070d0aefff",
    "8bd36070d0c0fff",
    "8bd36070d0c1fff",
    "8bd36070d0c2fff",
    "8bd36070d0c3fff",
    "8bd36070d0c4fff",
    "8bd36070d0c6fff",
    "8bd36070d0c8fff",
    "8bd36070d0cafff",
    "8bd36070d0cbfff",
    "8bd36070d0cefff",
    "8bd36070d0d5fff",
    "8bd36070d0d9fff",
    "8bd36070d0dcfff",
    "8bd36070d0ddfff",
    "8bd36070d0f0fff",
    "8bd36070d0f1fff",
    "8bd36070d0f2fff",
    "8bd36070d0f3fff",
    "8bd36070d0f4fff",
    "8bd36070d0f5fff",
    "8bd36070d0f6fff",
    "8bd36070d18bfff",
    "8bd36070d392fff",
    "8bd36070d393fff",
    "8bd36070d396fff",
    "8bd36070d760fff",
    "8bd36070d761fff",
    "8bd36070d764fff",
    "8bd36070d765fff",
    "8bd36070d768fff",
    "8bd36070d76cfff",
    "8bd36070d76dfff",
    "8bd36070d76efff",
  ],
  gapped: [
    "8bd36070d012fff",
    "8bd36070d013fff",
    "8bd36070d016fff",
    "8bd36070d01afff",
    "8bd36070d0a0fff",
    "8bd36070d0a1fff",
    "8bd36070d0a4fff",
    "8bd36070d0a5fff",
    "8bd36070d0a8fff",
    "8bd36070d0a9fff",
    "8bd36070d0abfff",
    "8bd36070d0acfff",
    "8bd36070d0adfff",
    "8bd36070d0aefff",
    "8bd36070d0c0fff",
    "8bd36070d0c2fff",
    "8bd36070d0c4fff",
    "8bd36070d0c6fff",
    "8bd36070d0d5fff",
    "8bd36070d0f0fff",
    "8bd36070d0f1fff",
    "8bd36070d0f2fff",
    "8bd36070d0f3fff",
    "8bd36070d0f4fff",
    "8bd36070d0f5fff",
    "8bd36070d0f6fff",
    "8bd36070d18bfff",
    "8bd3607540c0fff",
    "8bd3607540c2fff",
    "8bd3607540c3fff",
    "8bd3607540c6fff",
    "8bd3607540cafff",
    "8bd3607540cbfff",
    "8bd3607540cefff",
    "8bd3607540d1fff",
    "8bd3607540d5fff",
    "8bd3607540d8fff",
    "8bd3607540d9fff",
    "8bd3607540dcfff",
    "8bd3607540ddfff",
    "8bd360754392fff",
    "8bd360754760fff",
    "8bd360754761fff",
    "8bd360754763fff",
    "8bd360754764fff",
    "8bd360754765fff",
    "8bd360754766fff",
    "8bd360754768fff",
    "8bd360754769fff",
    "8bd36075476afff",
    "8bd36075476bfff",
    "8bd36075476cfff",
    "8bd36075476dfff",
    "8bd36075476efff",
  ],
  loop: [
    "8bd36070d012fff",
    "8bd36070d013fff",
    "8bd36070d016fff",
    "8bd36070d01afff",
    "8bd36070d0a0fff",
    "8bd36070d0a1fff",
    "8bd36070d0a4fff",
    "8bd36070d0a5fff",
    "8bd36070d0a8fff",
    "8bd36070d0a9fff",
    "8bd36070d0abfff",
    "8bd36070d0acfff",
    "8bd36070d0adfff",
    "8bd36070d0aefff",
    "8bd36070d0c0fff",
    "8bd36070d0c1fff",
    "8bd36070d0c2fff",
    "8bd36070d0c3fff",
    "8bd36070d0c4fff",
    "8bd36070d0c6fff",
    "8bd36070d0cefff",
    "8bd36070d0d5fff",
    "8bd36070d0d8fff",
    "8bd36070d0dafff",
    "8bd36070d0dcfff",
    "8bd36070d0ddfff",
    "8bd36070d0defff",
    "8bd36070d0f0fff",
    "8bd36070d0f1fff",
    "8bd36070d0f2fff",
    "8bd36070d0f3fff",
    "8bd36070d0f4fff",
    "8bd36070d0f5fff",
    "8bd36070d0f6fff",
    "8bd36070d18bfff",
    "8bd36070d440fff",
    "8bd36070d441fff",
    "8bd36070d443fff",
    "8bd36070d444fff",
    "8bd36070d445fff",
    "8bd36070d446fff",
    "8bd36070d448fff",
    "8bd36070d449fff",
    "8bd36070d44afff",
    "8bd36070d44bfff",
    "8bd36070d44cfff",
    "8bd36070d44dfff",
    "8bd36070d44efff",
    "8bd36070d462fff",
    "8bd36070d463fff",
    "8bd36070d46afff",
    "8bd36070d471fff",
    "8bd36070d475fff",
    "8bd36070d701fff",
    "8bd36070d703fff",
    "8bd36070d70cfff",
    "8bd36070d70efff",
    "8bd36070d710fff",
    "8bd36070d711fff",
    "8bd36070d712fff",
    "8bd36070d713fff",
    "8bd36070d714fff",
    "8bd36070d716fff",
    "8bd36070d718fff",
    "8bd36070d71afff",
    "8bd36070d71cfff",
    "8bd36070d71dfff",
    "8bd36070d71efff",
    "8bd36070d728fff",
    "8bd36070d729fff",
    "8bd36070d72afff",
    "8bd36070d72bfff",
    "8bd36070d72dfff",
    "8bd36070d7a5fff",
    "8bd36070d7a9fff",
    "8bd36070d7acfff",
    "8bd36070d7adfff",
  ],
  teleport: [
    "8bd3606b4848fff",
    "8bd3606b4849fff",
    "8bd3606b484afff",
    "8bd3606b484bfff",
    "8bd3606b4a30fff",
    "8bd3606b4a34fff",
    "8bd3606b4a35fff",
    "8bd3606b4b10fff",
    "8bd3606b4b12fff",
    "8bd3606b4b13fff",
    "8bd3606b4b16fff",
    "8bd3606b4b1afff",
    "8bd3606b4b1bfff",
    "8bd3606b4b1efff",
    "8bd3606b4ba5fff",
    "8bd3606b4ba9fff",
    "8bd3606b4bacfff",
    "8bd3606b4badfff",
    "8bd36070d012fff",
    "8bd36070d013fff",
    "8bd36070d016fff",
    "8bd36070d01afff",
    "8bd36070d0a0fff",
    "8bd36070d0a1fff",
    "8bd36070d0a4fff",
    "8bd36070d0a5fff",
    "8bd36070d0a8fff",
    "8bd36070d0a9fff",
    "8bd36070d0abfff",
    "8bd36070d0acfff",
    "8bd36070d0adfff",
    "8bd36070d0aefff",
    "8bd36070d0f0fff",
    "8bd36070d0f2fff",
    "8bd36070d0f3fff",
    "8bd36070d0f4fff",
    "8bd36070d0f5fff",
    "8bd36070d0f6fff",
    "8bd36070d18bfff",
  ],
}

describe("traceToSegments — the extraction preserved traceToCells (0195 criterion 1)", () => {
  const cases: Record<string, Trace> = {
    straight: trace(line(NEMO, 0, 40, 20)),
    gapped: trace(
      [...line(NEMO, 0, 20, 20), ...line(step(NEMO, 5_000, 0), 0, 20, 20, 3, 900_000)],
      [[19, 20]],
    ),
    loop: trace([
      ...line(NEMO, 0, 25, 20),
      ...line(step(NEMO, 500, 0), Math.PI / 2, 25, 20, 3, 170_000),
      ...line(step(step(NEMO, 500, 0), 500, Math.PI / 2), Math.PI, 25, 20, 3, 340_000),
    ]),
    teleport: trace([
      ...line(NEMO, 0, 15, 20),
      ...line(step(NEMO, 30_000, Math.PI / 2), 0, 15, 20, 3, 100_000),
    ]),
  }

  for (const [name, t] of Object.entries(cases)) {
    it(`emits exactly the pre-extraction cells for ${name}`, () => {
      expect([...traceToCells(t)].sort()).toEqual(PRE_EXTRACTION[name])
    })
  }

  it("emits nothing for an empty trace, as it did before", () => {
    expect([...traceToCells(trace([]))]).toEqual([])
  })

  it("reports the same rejects through both entry points", () => {
    const t = trace(line(NEMO, 0, 30, 20))
    expect(traceToSegments(t).rejects).toEqual(traceToCells(t).rejects)
  })

  it("counts one segment per piece steps 1-3 left behind", () => {
    const t = trace(line(NEMO, 0, 30, 20))
    const { segments, rejects } = traceToSegments(t)
    expect(rejects.segments).toBe(segments.length)
  })
})

describe("traceToSegments — the joining chords never exist (0057 criterion 8)", () => {
  /**
   * THE CASE `0057` CANNOT GET WRONG. A trace split by a 15-minute gap 5 km from where it
   * resumes must not leave a 5 km edge anywhere in the output — on the map that edge is a
   * straight line across a bay, and on a map that never re-fogs (D-020) it is permanent.
   *
   * Asserted as "no edge longer than the sampling spacing allows" rather than as a segment
   * count, because a count passes if the chord is inside one of the segments.
   */
  it("splits a gapped trace and draws no edge across the gap", () => {
    const first = line(NEMO, 0, 20, 20)
    const second = line(step(NEMO, 5_000, 0), 0, 20, 20, 3, 900_000)
    const { segments } = traceToSegments(trace([...first, ...second], [[19, 20]]))

    expect(segments.length).toBeGreaterThan(1)
    for (const segment of segments) {
      for (let i = 1; i < segment.length; i++) {
        // The 5 km chord would be two orders of magnitude over the 20 m sampling step.
        expect(metres(segment[i - 1]!, segment[i]!)).toBeLessThan(200)
      }
    }
  })

  it("leaves the two pieces at their real distance from one another", () => {
    const first = line(NEMO, 0, 20, 20)
    const second = line(step(NEMO, 5_000, 0), 0, 20, 20, 3, 900_000)
    const { segments } = traceToSegments(trace([...first, ...second], [[19, 20]]))

    const last = segments[0]!.at(-1)!
    const next = segments[1]![0]!
    // The gap is REAL and stays real. A renderer draws two lines with a hole between them;
    // nothing here quietly bridges it, and nothing here pretends it was never there.
    expect(metres(last, next)).toBeGreaterThan(4_000)
  })
})
