import { describe, expect, it } from "vitest"

import type { GeoPoint, Trace } from "./activity"
import { traceToCells, traceToSegments } from "./fog"

/**
 * Ticket `0195`. `05-fog-of-war.md` §2.2 steps 1-3.
 *
 * `traceToSegments` was extracted out of `traceToCells` so the drawn route and the revealed
 * ground come from one sanitation path. Two things have to stay true, and they are the whole
 * of this file: the extraction changed no cell, and the chords between segments do not exist.
 *
 * GEOMETRY IS SYNTHETIC, near Point Nemo — `08-security-privacy.md` §7.2, D-199. This
 * repository is public.
 */

const NEMO = { lat: -48.876, lng: -123.393 }
const R_EARTH = 6_371_008.8
const toRad = (d: number) => (d * Math.PI) / 180
const toDeg = (r: number) => (r * 180) / Math.PI

function step(from: { lat: number; lng: number }, metres: number, bearing: number) {
  return {
    lat: from.lat + toDeg((metres * Math.cos(bearing)) / R_EARTH),
    lng: from.lng + toDeg((metres * Math.sin(bearing)) / (R_EARTH * Math.cos(toRad(from.lat)))),
  }
}

function line(
  from: { lat: number; lng: number },
  bearing: number,
  count: number,
  spacingM: number,
  speedMs = 3,
  t0 = 0,
): GeoPoint[] {
  const out: GeoPoint[] = []
  for (let i = 0; i < count; i++) {
    const p = step(from, i * spacingM, bearing)
    out.push({ ...p, t: t0 + Math.round((i * spacingM * 1000) / speedMs) })
  }
  return out
}

function trace(points: GeoPoint[], gaps: Array<[number, number]> = []): Trace {
  const lats = points.map((p) => p.lat)
  const lngs = points.map((p) => p.lng)
  return {
    points,
    gaps,
    simplified: false,
    bbox: points.length
      ? [Math.min(...lngs), Math.min(...lats), Math.max(...lngs), Math.max(...lats)]
      : [0, 0, 0, 0],
    pointCount: points.length,
  }
}

const metres = (a: GeoPoint, b: GeoPoint): number => {
  const dLat = toRad(b.lat - a.lat)
  const dLng = toRad(b.lng - a.lng) * Math.cos(toRad((a.lat + b.lat) / 2))
  return Math.hypot(dLat, dLng) * R_EARTH
}

/**
 * THE CELL SETS THE PRE-EXTRACTION `traceToCells` PRODUCED, pinned. Criterion 1.
 *
 * Not a snapshot of what the code currently does — these were generated by running
 * `git show HEAD:src/domain/fog.ts` (the version before `traceToSegments` was pulled out of it)
 * against the four traces below, and only then written down. A snapshot taken after the change
 * would assert that the refactor agrees with itself, which is the exact assurance a refactor
 * needs and the exact assurance a self-comparison cannot give.
 *
 * They are ids and not counts because D-020 makes a cell permanent: a refactor that dropped one
 * cell and gained another passes every count check ever written.
 */
const PRE_EXTRACTION: Record<string, string[]> = {
  straight: [
    "8ad36070d0a7fff",
    "8ad36070d0affff",
    "8ad36070d0c7fff",
    "8ad36070d0cffff",
    "8ad36070d0f7fff",
    "8ad36070d767fff",
    "8ad36070d76ffff",
  ],
  gapped: [
    "8ad36070d0a7fff",
    "8ad36070d0affff",
    "8ad36070d0c7fff",
    "8ad36070d0f7fff",
    "8ad3607540c7fff",
    "8ad3607540dffff",
    "8ad360754767fff",
    "8ad36075476ffff",
  ],
  loop: [
    "8ad36070d0a7fff",
    "8ad36070d0affff",
    "8ad36070d0c7fff",
    "8ad36070d0dffff",
    "8ad36070d0f7fff",
    "8ad36070d447fff",
    "8ad36070d44ffff",
    "8ad36070d717fff",
    "8ad36070d71ffff",
    "8ad36070d72ffff",
  ],
  teleport: [
    "8ad3606b484ffff",
    "8ad3606b4a37fff",
    "8ad3606b4b17fff",
    "8ad36070d0a7fff",
    "8ad36070d0affff",
    "8ad36070d0f7fff",
  ],
}

describe("traceToSegments — the extraction preserved traceToCells (0195 criterion 1)", () => {
  const cases: Record<string, Trace> = {
    straight: trace(line(NEMO, 0, 40, 20)),
    gapped: trace(
      [...line(NEMO, 0, 20, 20), ...line(step(NEMO, 5_000, 0), 0, 20, 20, 3, 900_000)],
      [[19, 20]],
    ),
    loop: trace([
      ...line(NEMO, 0, 25, 20),
      ...line(step(NEMO, 500, 0), Math.PI / 2, 25, 20, 3, 170_000),
      ...line(step(step(NEMO, 500, 0), 500, Math.PI / 2), Math.PI, 25, 20, 3, 340_000),
    ]),
    teleport: trace([
      ...line(NEMO, 0, 15, 20),
      ...line(step(NEMO, 30_000, Math.PI / 2), 0, 15, 20, 3, 100_000),
    ]),
  }

  for (const [name, t] of Object.entries(cases)) {
    it(`emits exactly the pre-extraction cells for ${name}`, () => {
      expect([...traceToCells(t)].sort()).toEqual(PRE_EXTRACTION[name])
    })
  }

  it("emits nothing for an empty trace, as it did before", () => {
    expect([...traceToCells(trace([]))]).toEqual([])
  })

  it("reports the same rejects through both entry points", () => {
    const t = trace(line(NEMO, 0, 30, 20))
    expect(traceToSegments(t).rejects).toEqual(traceToCells(t).rejects)
  })

  it("counts one segment per piece steps 1-3 left behind", () => {
    const t = trace(line(NEMO, 0, 30, 20))
    const { segments, rejects } = traceToSegments(t)
    expect(rejects.segments).toBe(segments.length)
  })
})

describe("traceToSegments — the joining chords never exist (0057 criterion 8)", () => {
  /**
   * THE CASE `0057` CANNOT GET WRONG. A trace split by a 15-minute gap 5 km from where it
   * resumes must not leave a 5 km edge anywhere in the output — on the map that edge is a
   * straight line across a bay, and on a map that never re-fogs (D-020) it is permanent.
   *
   * Asserted as "no edge longer than the sampling spacing allows" rather than as a segment
   * count, because a count passes if the chord is inside one of the segments.
   */
  it("splits a gapped trace and draws no edge across the gap", () => {
    const first = line(NEMO, 0, 20, 20)
    const second = line(step(NEMO, 5_000, 0), 0, 20, 20, 3, 900_000)
    const { segments } = traceToSegments(trace([...first, ...second], [[19, 20]]))

    expect(segments.length).toBeGreaterThan(1)
    for (const segment of segments) {
      for (let i = 1; i < segment.length; i++) {
        // The 5 km chord would be two orders of magnitude over the 20 m sampling step.
        expect(metres(segment[i - 1]!, segment[i]!)).toBeLessThan(200)
      }
    }
  })

  it("leaves the two pieces at their real distance from one another", () => {
    const first = line(NEMO, 0, 20, 20)
    const second = line(step(NEMO, 5_000, 0), 0, 20, 20, 3, 900_000)
    const { segments } = traceToSegments(trace([...first, ...second], [[19, 20]]))

    const last = segments[0]!.at(-1)!
    const next = segments[1]![0]!
    // The gap is REAL and stays real. A renderer draws two lines with a hole between them;
    // nothing here quietly bridges it, and nothing here pretends it was never there.
    expect(metres(last, next)).toBeGreaterThan(4_000)
  })
})
