#!/usr/bin/env node
// Generates docs/INDEX.md — a section map so design docs are read by section,
// never whole (D-151, ticket 0120).
//
// The docs run 200-1800 lines each. Reading three of them end to end is most of
// a context window and leaves no room to work. This index exists so finding the
// right SECTION is cheap; without it, "read by section" is advice you cannot
// follow because you must open the file to learn what is in it.
//
// Summaries live in docs/.index-summaries.json, keyed by "file#heading", and are
// PRESERVED across regeneration. Line numbers move on every edit, so the index
// must be regenerated — but a hand-written summary must not be lost when it is.
//
//   node scripts/build-index.mjs           regenerate
//   node scripts/build-index.mjs --check   exit 1 if out of date (CI)

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const SIDECAR = join(ROOT, "docs/.index-summaries.json");
const OUT = join(ROOT, "docs/INDEX.md");

const FILES = [
  ...readdirSync(join(ROOT, "docs"))
    .filter((f) => f.endsWith(".md") && f !== "INDEX.md")
    .sort()
    .map((f) => `docs/${f}`),
  ...readdirSync(join(ROOT, "docs/contracts"))
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => `docs/contracts/${f}`),
];

/** First prose line under a heading, cleaned up, as a fallback summary. */
function derive(lines, from, to) {
  for (let i = from; i < Math.min(to, from + 14); i++) {
    let l = lines[i].trim();
    if (!l) continue;
    if (/^[#>|`\-*\d]/.test(l)) continue;      // heading, quote, table, code, list
    l = l
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") // links -> text
      .replace(/[*_`]/g, "")
      .replace(/\s+/g, " ")
      .trim();
    if (l.length < 12) continue;
    // A line ending in ':' is introducing a list, table or code block — it is a
    // label, not a statement, and yields summaries like "Justification:" which
    // are exactly the vagueness this index exists to avoid. Skip to real prose.
    if (/:$/.test(l)) continue;
    const stop = l.search(/\.\s|\.$/);
    if (stop > 24) l = l.slice(0, stop + 1);
    return l.length > 118 ? l.slice(0, 115).trimEnd() + "…" : l;
  }
  return "";
}

const sidecar = existsSync(SIDECAR) ? JSON.parse(readFileSync(SIDECAR, "utf8")) : {};
const nextSidecar = {};
const docs = [];

for (const rel of FILES) {
  const text = readFileSync(join(ROOT, rel), "utf8");
  const lines = text.split("\n");
  const heads = [];
  let inFence = false;

  lines.forEach((l, i) => {
    if (/^\s*```/.test(l)) inFence = !inFence;
    if (inFence) return;                        // '## ' inside a code block is not a heading
    const m = /^(#{1,3})\s+(.*\S)\s*$/.exec(l);
    if (m) heads.push({ level: m[1].length, title: m[2], line: i + 1 });
  });

  const title = heads.find((h) => h.level === 1)?.title ?? rel;
  const sections = heads.filter((h) => h.level >= 2);

  sections.forEach((h, idx) => {
    // range ends at the next heading of the same or higher level
    let end = lines.length;
    for (let j = idx + 1; j < sections.length; j++) {
      if (sections[j].level <= h.level) { end = sections[j].line - 1; break; }
    }
    const key = `${rel}#${h.title}`;
    const summary = sidecar[key] ?? derive(lines, h.line, end);
    nextSidecar[key] = summary;
    h.end = end;
    h.summary = summary;
  });

  docs.push({ rel, title, total: lines.length, sections });
}

const stamp = new Date().toISOString().slice(0, 10);
let out = `# Documentation index

> **Generated by \`scripts/build-index.mjs\`. Do not edit by hand** — line numbers move on every
> doc edit and a stale index is worse than none. Edit summaries in
> \`docs/.index-summaries.json\` instead; they are preserved across regeneration.

**Read by section, never whole** (D-151). These documents total ${docs.reduce((a, d) => a + d.total, 0).toLocaleString()} lines; three of
them end to end is most of a context window. Find the section here, then read only its range:

\`\`\`
sed -n '120,190p' docs/05-fog-of-war.md
\`\`\`

${docs.length} documents · ${docs.reduce((a, d) => a + d.sections.length, 0)} sections · regenerated ${stamp}

`;

for (const d of docs) {
  out += `\n## \`${d.rel}\`\n\n**${d.title}** — ${d.total.toLocaleString()} lines\n\n`;
  out += `| Section | Lines | Settles |\n|---|---|---|\n`;
  for (const s of d.sections) {
    const indent = s.level === 3 ? "&nbsp;&nbsp;↳ " : "";
    const t = s.title.replace(/\|/g, "\\|");
    const sum = (s.summary || "").replace(/\|/g, "\\|");
    out += `| ${indent}${t} | \`${s.line}-${s.end}\` | ${sum} |\n`;
  }
}

writeFileSync(SIDECAR, JSON.stringify(nextSidecar, null, 1) + "\n");

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  // ignore the regeneration date when comparing
  const norm = (s) => s.replace(/regenerated \d{4}-\d{2}-\d{2}/, "regenerated DATE");
  if (norm(current) !== norm(out)) {
    console.error("docs/INDEX.md is out of date. Run: node scripts/build-index.mjs");
    process.exit(1);
  }
  console.log("docs/INDEX.md is up to date.");
  process.exit(0);
}

writeFileSync(OUT, out);
console.log(
  `docs/INDEX.md: ${docs.length} documents, ` +
    `${docs.reduce((a, d) => a + d.sections.length, 0)} sections, ` +
    `${Object.values(nextSidecar).filter(Boolean).length} summaries.`
);
