// GENERATED by scripts/build-rules-json.mjs — do not edit. D-217, D-274, ticket 0234.
// Every ruleset version the ingest worker can score under, by number. Unvalidated here:
// the worker runs `assertValidRuleSet` on each at cold start.

import V1 from "./xp-rules-v1.json"
import V2 from "./xp-rules-v2.json"
import V3 from "./xp-rules-v3.json"

export const BUNDLED_RULES: Readonly<Record<number, unknown>> = {
  1: V1,
  2: V2,
  3: V3,
}
